all:
  children:
    qfx:
      hosts:
        dc1-leaf1:
          ansible_host: 100.123.24.5
          ansible_user: jcluser
          ansible_password: Juniper!1
          ansible_network_os: junipernetworks.junos.junos
          ansible_connection: ansible.netcommon.netconf
          ansible_python_interpreter: /home/jcluser/venv_ansible/bin/python

